### ISSUE TITLE
GET request when using no Committee::Middleware::RequestValidation

### ISSUE THREAD

**Issue by incorvia** [interagent/committee#109]
I have a simple rails index action say: GET#host.com/v1/plans.  When RequestValidation middlewhere in place, I get an error if I don't define a "schema" property:

    NoMethodError (undefined method `properties' for nil:NilClass):

If I do define a schema.. i don't know what schema to define as technically I'm just making a GET request with no actual parameters or data required. 

How do I handle this situation where I want to leave the RequestValidation middlewhere in but I have a simple get request with no actual schema.

**Comment by brandur** [comment]
Hi @incorvia, sorry to hear about the trouble here. This sounds like a bug.

Is there any chance that you were using parameter coercion? There was a recent fix in #111 for a problem that threw exactly this error message.

If not, could you get me the whole backtrace from the exception? Thanks!

**Comment by incorvia** [comment]
I'm not trying to explicitly use parameter coercion but perhaps I am just by using request and response validation middleware? Regardless, updating to pre5 seems to have fixed the issue so thank you for pointing out the new version!
