### ISSUE TITLE
Suggestion: behavior of StringParamsCoercer for boolean

### ISSUE THREAD

**Issue by qsona** [interagent/committee#110]
The current behavior that how StringParamsCoercer coerces string to boolean is:
https://github.com/interagent/committee/blob/a99f1b4f1eda0eb9c269efa6d55e451f5d1d3b81/lib/committee/string_params_coercer.rb#L39-L42

so, the `s` value is regarded as boolean, it coerces (or doesn't coerce) query such as follows.

```
?s=true #=> true
?s=false #=> false
?s=1 #=> "1"
?s= #=> ""
```

After the value passed through coercer, it is sometimes boolean but sometimes not. So application code needs more validation code and it often becomes a bit complicated.

As far as I know, there is no rule that how the form-urlencoded param should be coerced to boolean value,
but in my experience, `s=` is often regarded as `s: false`, and `s=1` as `s: true`. (Of course it's debatable. )

So, here is my suggestion: if the string value is empty or "false", it is coerced to false. else, it is coerced to true.

```
?s=1 #=> true
?s=asdf #=> true
?s= #=> false
```

Any thoughts? Thanks.

**Comment by qsona** [comment]
I checked a behavior of github, and I found that the following query are all regarded as `w:true`... 
even `?w=false` is treated as w:true.

https://github.com/interagent/committee/pull/104/files?w=1
https://github.com/interagent/committee/pull/104/files?w=
https://github.com/interagent/committee/pull/104/files?w=false

**Comment by brandur** [comment]
Interesting. I assume that this change would address a problem that you're running into to? (Worded otherwise, why do you want this exactly?)

Like you mention, it is quite commonly seen in web APIs in particular to be quite liberal when it comes to parsing values for booleans, and this does seem to comply well with Postel's Law. I am slightly worried though that we'd be make the change without a lot of well considered justification. Do you know of any other example languages/frameworks/libraries that parse booleans this way that we could at least point to as prior art to stay consistent with?

**Comment by qsona** [comment]
@brandur Thanks for your responding. I believe that boolean coercer should return true, false or nil, otherwise should fail. Now coercer may return string, so we need extra validation in application code. My problem is it.

Because this library is for Ruby, it may be better if this is compatible with other ruby libraries. I investigated some ruby libraries which are considered to have same feature. I'd like to add more result if I come up with some other libraries in Ruby.

### 1. Grape

grape is a library for building APIs in ruby.
https://github.com/ruby-grape/grape

Coercing code can be written in such way in grape.
```
# required
requires :bool, type: Boolean
# optional
optional :bool, type: Boolean
```

### 2. ActiveRecord

If we have Rails application and it doesn't have any validation or coercing code, it may be directly  passed to ActiveRecord Class in such way:
`model = SomeModel.new(bool: params[:bool])`

And then `model.bool` is the coerced value if the type definition of `SomeModel#bool` is boolean,.

### Comparison

|query/library|Grape(optional)|Grape(required)|ActiveRecord|
|:--|:--|:--|:--|
|(no query)|nil|Bad Request|nil|
|?bool=|nil|nil|nil|
|?bool=true|true|true|true|
|?bool=false|false|false|false|
|?bool=1|true|true|true|
|?bool=0|false|false|false|
|?bool=2|Bad Request|Bad Request|true|
|?bool=a|Bad Request|Bad Request|true|

**Comment by brandur** [comment]
@qsona Thanks for the detailed research here! I'm pretty convinced that we could implemented `true`/`false`/`1`/`0`. Any interest in taking a shot at a patch?

**Comment by qsona** [comment]
@brandur I agree that true/1 should be treated as true, and false/0 as false.
How to treat other values such as `2`? In my opinion, other values should be coerced to nil. (Then the request fails as 400 Bad request if the parameter is required)

> Any interest in taking a shot at a patch?

Sorry I don't understand... Do you mean that am I interested in sending a PR? If so, Yes :)

**Comment by brandur** [comment]
@qsona

> How to treat other values such as 2? In my opinion, other values should be coerced to nil. (Then the request fails as 400 Bad request if the parameter is required)

So the coercer currently throws an exception when [it hits an invalid date-time](https://github.com/interagent/committee/blob/8b87bdb4ec6dd834ae104c2e5ad9651de8c3212a/lib/committee/parameter_coercer.rb#L37). I think it makes sense to duplicate this behavior here.

> Sorry I don't understand... Do you mean that am I interested in sending a PR? If so, Yes :)

Yes that's what I meant :) And great!

**Comment by qsona** [comment]
Sorry, I misunderstood the current behavior, or I mixed up two different points.
For the first point, I sent a PR #116 so please have a look :)
The second point I thought is that if we specify that the key is `boolean` in json schema then the value should be assured to be boolean or nil. I just found that this problem is not limited for boolean. I'm not good to describe with sentences, so please let me add some test codes and send a WIP PR later.

**Comment by brandur** [comment]
> The second point I thought is that if we specify that the key is boolean in json schema then the value should be assured to be boolean or nil. I just found that this problem is not limited for boolean. I'm not good to describe with sentences, so please let me add some test codes and send a WIP PR later.

Sounds good. Thanks!

**Comment by qsona** [comment]
@brandur I'm ashamed to say, but perhaps my understanding was completely wrong. I think my report was really confusing. 

1) I was misreading the code.
https://github.com/interagent/committee/blob/a99f1b4f1eda0eb9c269efa6d55e451f5d1d3b81/lib/committee/string_params_coercer.rb#L39-L42
First I thought that if the value isn't in true/false/1/0 then value is not coerced so the value is passed to application as string. But actually it doesn't pass through request validator so it does not occur.

2) At some time I thought It occurred on my project, but I can't reproduce it. Perhaps I didn't write schema, or I wrote wrong URI.
I also wrote following test case in test/middleware/request_validation_test.rb, and it passes as expected.

```rb
    @app = new_rack_app(schema: hyper_schema)
    params = {
      "maintenance" => "some unexpected value"
    }
    header "Content-Type", "application/json"
    patch "/apps/aaa", JSON.generate(params)
    assert_equal 400, last_response.status
```

Could you please point out I still seem to have a misunderstanding?

Thanks.

**Comment by brandur** [comment]
Hi @qsona, so just to clarify: you're saying that there's a bug in the current implementation, and that bug is that if coercing is enabled and a field is _not_ a boolean value, then no value appears in the final output?

(Sorry for the delay.)
