### ISSUE TITLE
`coerce_form_params` option is not documented in README

### ISSUE THREAD

**Issue by qsona** [interagent/committee#114]
Could you add description of `coerce_form_params` option to README.md? Sorry, I'm not a native English speaker so it's difficult for me.
(P.S. This option seems to be working well for my project.)

**Comment by brandur** [comment]
Yep! Oops, my mistake overlooking that one. Added in 700b64d. Thanks as usual!

**Comment by qsona** [comment]
Thank you! I can learn a lot from your English.

**Comment by brandur** [comment]
@qsona Anytime! Thanks as usual for the continued contributions to the project :)
