### ISSUE TITLE
Allow skipping committee validation

### ISSUE THREAD

**Issue by kts15** [interagent/committee#138]
## Summary
I want to skip committee validation by passing a env option or something.

## Why
Sometime, we want to parse errors of raised by committee so that we can translate other language (ex: Japanese or Chinese) or we can log according to type of error.

And when we create parsing module ,  we have to except that internal errors of the parsing module may happen.

To catch errors happened in the layer of middleware(is committee, in this context), it is sufficient to arrange a dedicated module above committee in middleware stack.

However, what should we do when we want to ignore  internal errors of the parsing module and return to application process, or when catch committee-raised-error just to log and return to application process?
(Just calling `@app.call(env)` causes committee’s error again!)

I wish we can skip committee’s validation when we use `@app.call(env)` in a specific way, 

## How
For example, I think it’s good if we set env[‘skip_committee_validation’] true, committee just call @app.call(env).
Specifically, in `lib/committee/middleware/base.rb`,

```diff
def call(env)
  request = Rack::Request.new(env)

-if @router.includes_request?(request)
+if @router.includes_request?(request) && !env['skip_committee_validation']  # check env option here
    handle(request)
  else
    @app.call(request.env)
   end
end
```

If you agree with this, I will create a pull request. 
Thank you for reading.

**Comment by ota42y** [comment]
I agree with you 👍👍👍

But I want a more detailed use case.
I think when we get error and skip validation, I think we need to be able to get the error contents.
So if you tell us more detailed use case, we can discuss what kind of information is necessary.

**Comment by qsona** [comment]
@kts15 I have the same problem consciousness.
I'm not sure that your suggestion of `env['skip_committee_validation']` is really needed - Isn't it enough that just choosing whether do `use Committee::Middleware::RequestValidation` or not by environment?

But I agree with your motivation. I want to do customize validator behavior, for example:

- Customize response json
- Output Log / Send error to some external service (e.g. Sentry)

**Comment by kts15** [comment]
@ota42y  @qsona 

I'm glad for you to understand this problem, and I think there are many other developers who cares about it.

>  I think when we get error and skip validation, I think we need to be able to get the error contents.

I should have explained that our application is also preparing minimum validation on the application side.
So, if an internal error occurs in the module to parse the error, we can skip the committee validation.

> Isn't it enough that just choosing whether do use Committee::Middleware::RequestValidation or not by environment?

Actually not enough.
By `use Committee::Middleware::RequestValidation`, whether middleware validation should be done is decided only when an application(ex: Rails) is started.

However, comprehensively thinking, what I suggested(decide whether doing validation depend on `env['skip_committee_validation']`) may have been our unique solution, so this time I will just apply monkey patch.

As @qsona commented, my(and maybe also your) goal is,

- Customize response json
- Output Log 

If you do not need to write a code with complex long logic in the module for parse, you do not need to think too much about the internal error of that module.
So, for example, what we can do is

- Make it possible to choose a json validator library other than [this](https://github.com/brandur/json_schema) by giving a option to `use Committee::Middleware::RequestValidation`
  - By customizing this library, request validation will raise only error with invalid field of request & type of errors, or translated error message.

I'm considering what solution is best, and I'll never give up using committee more effectively.
I may ask you for help again! Thank you.
