### ISSUE TITLE
Feature Request: handle InvalidResponse Error but not change the original response 

### ISSUE THREAD

**Issue by qsona** [interagent/committee#217]
Especially in the production environment, we sometimes want to enable the `Committee::ResponseValidation` and just notify an alert to Slack or Sentry etc, but still return the original response.
As far as I understand, the middleware makes the response as status:500 by default, and it can be customized but I don't find the way to just respond with the original.

**Comment by ota42y** [comment]
Certainly, it makes sense that you only want to take logs in production to avoid false positives.
I'll add `ignore_error` option to response validator.
This option ignore validation error and always return original data.
