### ISSUE TITLE
Feature request: check response headers

### ISSUE THREAD

**Issue by genya0407** [interagent/committee#237]
I want to assert whether a *response* header matches OpenAPI definition.

There is `check_header` option already, but it seems to check only *request* headers. And there is no way to check *response* headers.

## Example

Given following schema,

```yaml
openapi: 3.0.0
info:
  title: Sample API
  version: 0.1.0

paths:
  /auth/sign_in:
    post:
      operationId: SignIn
      summary: Sign in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: A User auth object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                  name:
                    type: string
          headers:
            access-token:
              schema:
                type: string
```

the following test is expected to fail because the server responses with wrong header key.

```ruby
class ResponseHeaderTest < Test::Unit::TestCase
  include Committee::Test::Methods
  include Rack::Test::Methods

  def app
    Sinatra.new do
      post "/auth/sign_in" do
        content_type :json
        headers['access-tokem'] = 'token' # header key typo
        JSON.generate(email: 'example@example.com', name: 'Some User Name')
      end
    end
  end

  def test_response_header_conforms
    post "/auth/sign_in", JSON.generate(email: 'example@example.com', password: 'somepassword')
    assert_response_schema_confirm # assertion should fail
  end
end
```

**Comment by genya0407** [comment]
This line seems the point.
https://github.com/interagent/committee/blob/master/lib/committee/schema_validator/open_api_3/operation_wrapper.rb#L33
The response header is not checked here.

**Comment by genya0407** [comment]
committee uses `OpenAPI::Parser` v0.2.2 to check response ( https://github.com/interagent/committee/blob/master/committee.gemspec#L22 ).
However, `OpenAPI::Parser` v0.2.2 does not seem to support response header validation.

Fortunately, response header validation is supported in v0.4.0 ( https://github.com/ota42y/openapi_parser/commit/c393c43a2b9ecd834eeca9fe32a168039fb44694 ).
So we will get response header validation feature by upgrading `OpenAPI::Parser`'s version

**Comment by ota42y** [comment]
Now committee require openapi_parser 0.6.1 or later so I think this problem already solved :)
(I find other bug in header ... but this issue is already solved 😈  )
