### ISSUE TITLE
Using readOnly and required fails

### ISSUE THREAD

**Issue by Linuus** [interagent/committee#289]
Hi!

I have a schema where an attribute `type` is marked as `readOnly`. It cannot be set or updated but it is always returned.
Now, to make Committee validate (in my tests) that this attribute is _always_ returned, I need to also mark it as `required`. But when I mark it as `required` Committee throws an `InvalidRequest` error (when calling `assert_schema_conform`) if I _don't_ pass it in my `PATCH` request in my tests.

It should actually fail _if_ I pass the `type` attribute in the `PATCH` request.

Or am I wrong here? 🤔

**Comment by ota42y** [comment]
Could you tell me a little more about it?

- What kind of Schema definition is it?
- What kind of request are you sending

**Comment by Linuus** [comment]
This is a stripped down version of the schema (OpenAPI 3).

```yml
---
openapi: 3.0.0
info:
  version: 1.0.0
  title: Foobar API
  description: ''
servers:
- url: https://api.kisi.io
  description: ''
security: []
x-tagGroups:
paths:
  "/foobars":
    get:
      summary: Retrieves the foobars.
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Foobar"
  "/foobars/{id}":
    patch:
      parameters:
        - $ref: "#/components/parameters/id"
      requestBody:
        "$ref": "#/components/requestBodies/updateFoobar"
      responses:
        "204":
          description: no content
components:
  parameters:
    id:
      name: id
      in: path
      required: true
      schema:
        type: integer
        description: The ID of the record.
        readOnly: true
      description: The ID of the record.
  schemas:
    Foobar:
      type: object
      properties:
        type:
          type: string
          enum:
            - foo
            - bar
          description: The type of the foobar.
          readOnly: true
      required:
        - type
  requestBodies:
    updateFoobar:
      content:
        application/json:
          schema:
            type: object
            properties:
              foobar:
                $ref: "#/components/schemas/Foobar"
```

So, in this case, the `type` field is both `readOnly` (cannot be set) and _also_ `required` as in, it will _always_ be returned by the server (I want Committee to validate that I always return the `type` field).

So, the since the `type` field is `readOnly` it shouldn't be required for the PATCH. If you paste the above schema at: https://editor.swagger.io/ for instance, you can see that the `type` field is marked as required in responses, but not shown in the PATCH request.

**Comment by Linuus** [comment]
This is a stripped down version of the schema (OpenAPI 3).

```yml
---
openapi: 3.0.0
info:
  version: 1.0.0
  title: Foobar API
  description: ''
servers:
- url: https://api.example.com
  description: ''
security: []
paths:
  "/foobars":
    get:
      summary: Retrieves the foobars.
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Foobar"
  "/foobars/{id}":
    patch:
      parameters:
        - $ref: "#/components/parameters/id"
      requestBody:
        "$ref": "#/components/requestBodies/updateFoobar"
      responses:
        "204":
          description: no content
components:
  parameters:
    id:
      name: id
      in: path
      required: true
      schema:
        type: integer
        description: The ID of the record.
        readOnly: true
      description: The ID of the record.
  schemas:
    Foobar:
      type: object
      properties:
        type:
          type: string
          enum:
            - foo
            - bar
          description: The type of the foobar.
          readOnly: true
      required:
        - type
  requestBodies:
    updateFoobar:
      content:
        application/json:
          schema:
            type: object
            properties:
              foobar:
                $ref: "#/components/schemas/Foobar"
```

So, in this case, the `type` field is both `readOnly` (cannot be set) and _also_ `required` as in, it will _always_ be returned by the server (I want Committee to validate that I always return the `type` field).

So, the since the `type` field is `readOnly` it shouldn't be required for the PATCH. If you paste the above schema at: https://editor.swagger.io/ for instance, you can see that the `type` field is marked as required in responses, but not shown in the PATCH request.

**Comment by ota42y** [comment]
The committee doesn't support readOnly / writeOnly yet. 😢 
(So I close and move to this issue https://github.com/interagent/committee/issues/276)
