### ISSUE TITLE
divide parameter

### ISSUE THREAD

**Issue by ota42y** [interagent/committee#316]
# Plan
Now we override path parameter and query parameter so we can't get same name parameter like this
`curl -X POST --header 'Content-Type: application/json' -d '{"id": 82}' "localhost:3000/posts/21?id=42"`

So I want to divide path, query, request body parameter.
These parameter store env by individual key like this.

```
env['committee.params']['id'], 84 # use path parameter for merged params (like rails)
env['committee.path_hash']['id'], 21
env['committee.query_hash']['id'], 42
env['committee.request_body_hash']['id'], 84
```

And we can get merged parameter by specific key.
Because backward compatibility and when we want to use commitee in rails, we need set `action_dispatch.request.request_parameters`  
https://github.com/interagent/committee#use-ruby-on-rails-with-coerce-option

# Tasks
- [x] support path item's only validation in openapi_parser
- [x] add 'commitee.request_body_hash` option

# Other
related issue https://github.com/interagent/committee/issues/106
add failed tests https://github.com/interagent/committee/tree/feature/parameter_merge

**Comment by ota42y** [comment]
implemented path_hash_key option
https://github.com/interagent/committee/pull/318

**Comment by hlascelles** [comment]
Can we proceed with this issue now that https://github.com/interagent/committee/pull/322 is done? Happy to help if given a kick start.

**Comment by ota42y** [comment]
Yes, this change is now workable, please see [this issue](https://github.com/interagent/committee/issues/339)

**Comment by ota42y** [comment]
support by 5.0.0 https://github.com/interagent/committee/pull/349
