### ISSUE TITLE
Raise error in strict mode when missing response code

### ISSUE THREAD

**Issue by hiddewie** [interagent/committee#317]
This is a feature request.

Let's assume we have an OpenAPI specification with an API which is tested well. I run Committee in strict mode, such that Committee raises errors in case of missing path/method combinations. This works perfectly.

However, responses with a HTTP response (status) code that is not documented are ignored. In addition, no content validation is performed which can introduce breaking changes in the API that go unnoticed.

Instead, when a response is validated by Committee for which no response code is documented, an error should be raised.

Thanks in advance.

**Comment by ota42y** [comment]
Thank you your feedback!!!

Currently response validation does not support the strict option.
https://github.com/interagent/committee#committeemiddlewareresponsevalidation

I think some users set strict option to response validation and these users will get error when we support strict option.
So we should major update for supporting this option.
(We are planning 5.0.0 release so this change will include this version)

**Comment by hiddewie** [comment]
Thanks for the reaction. 

If people set configuration that is unsupported (`strict` on response validation), it is their probem right? I imagine it is impossible to be backwards compatible for undefined configuration.

Maybe they even expect strict response code validation when they set `strict` to true, even when it is not implemented right now.
