### ISSUE TITLE
Support POST request with JSON body and query parameters

### ISSUE THREAD

**Issue by justinlittman** [interagent/committee#328]
For example:
```
  /v1/objects:
    post:
      parameters:
        - in: query
          name: assign_doi
          schema:
            type: boolean
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/RequestDRO'
                - $ref: '#/components/schemas/RequestCollection'
                - $ref: '#/components/schemas/RequestAdminPolicy'
```
Note that the schemas referenced had `additionalProperties` set to false. (Setting `additionalProperties` to true allowed the validation to succeed.)

When posting, the validation is performed against a merging of the parsed JSON body and the query parameters.

For example:
```
post '/v1/objects?assign_doi=true',
               params: data,
               headers: { 'Authorization' => "Bearer #{jwt}", 'Content-Type' => 'application/json' }
```
(where `data` is a JSON string)
results in:
```
Committee::InvalidRequest:
       {"assign_doi"=>true, "type"=>"http://cocina.sul.stanford.edu/models/image.jsonld", "label"=>"This is my label", "version"=>1, "access"=>{"access"=>"world", "download"=>"none", "copyright"=>"All rights reserved unless otherwise indicated.", "useAndReproductionStatement"=>"Property rights reside with the repository..."}, "administrative"=>{"releaseTags"=>[], "hasAdminPolicy"=>"druid:dd999df4567", "partOfProject"=>"Google Books"}, "description"=>{"title"=>[{"value"=>"This is my title"}], "purl"=>"http://purl.stanford.edu/gg777gg7777", "access"=>{"digitalRepository"=>[{"value"=>"Stanford Digital Repository"}]}}, "identification"=>{"sourceId"=>"googlebooks:999999", "barcode"=>"36105036289127"}, "structural"=>{}} isn't one of in #/paths/~1v1~1objects/post/requestBody/content/application~1json/schema
```

Notice that the `assign_doi` query parameter is being evaluated as part of the request body validation.

This may because committee is using Rails request params, which merges both types of parameters: https://github.com/interagent/committee/blob/master/lib/committee/schema_validator/open_api_3/request_validator.rb#L18

**Comment by ota42y** [comment]
Ok, I found bug in master so we should fix it.

Now we save individual parameters to `request.env`
https://github.com/interagent/committee/blob/master/lib/committee/schema_validator/open_api_3.rb#L75-L79

But, schema validator doesn't support yet so we use merged parameter.
https://github.com/interagent/committee/blob/master/lib/committee/schema_validator/open_api_3.rb#L59

**Comment by eric-christian** [comment]
Hello

Just wanted to let you know that  we ran into that problem, too.
Any updates on a solution? The PR from @quentindemetz looks promising.

Have a great day! :)
