### ISSUE TITLE
Committee wrongly says that `head` is not supported in OpenAPI v3

### ISSUE THREAD

**Issue by Pritilender** [interagent/committee#330]
Running committee with a schema that has `head` method raises following error:

```
RuntimeError:
       Committee OpenAPI3 not support head method
```

But [OpenAPI v3 spec](https://github.com/OAI/OpenAPI-Specification/blob/92df7cacd80695a2b7aa56351dbef2b1a6fb6983/schemas/v3.0/schema.yaml) says it's supported. I can also confirm that schema is properly rendered in ReDoc.

**Comment by januszm** [comment]
@ota42y any chance this can be released as 4.x before 5 milestone?
