### ISSUE TITLE
support individual key for validation

### ISSUE THREAD

**Issue by ota42y** [interagent/committee#339]
Now schema validator doesn't support yet so we use merged parameter.
https://github.com/interagent/committee/blob/master/lib/committee/schema_validator/open_api_3.rb#L59

This problem caused this issue #328 
So we should validation by individual key.

# Add `validate_by_merged_param` option
To avoid breaking backward compatibility, we should add this option and do old validation.

# save query hash to key
Now we save query hash to merged key
https://github.com/interagent/committee/blob/20de9adcbd57e68d68d2a5aa7d483db40165ab91/lib/committee/schema_validator/open_api_3.rb#L81-L84

The last step in validation, we copy query hash to individual key
https://github.com/interagent/committee/blob/20de9adcbd57e68d68d2a5aa7d483db40165ab91/lib/committee/schema_validator/open_api_3.rb#L89-L99

But this is bad code.
We should copy to individual key in request_unpack method.

```
        request.env[validator_option.params_key]= unpacker.unpack_query_params(request)
```

# validate query parameter and request parameter
Now we check parameter by method name.
This method expect only one and merged parameter
https://github.com/interagent/committee/blob/1d9b9245413acf6f37fcd156961561d1946a214a/lib/committee/schema_validator/open_api_3/operation_wrapper.rb#L42-L58

So we need to fix this method to get individual parameter and merge it like this.

```ruby
        def validate_request_params(query_param, path_hash, request_body_hash, headers, validator_option)
          request_operation.validate_request_parameter(query_param, headers, build_openapi_parser_get_option(validator_option))
          request_operation.validate_request_body(content_type, params, schema_validator_options)   
        end
```

**Comment by ota42y** [comment]
this change resolve https://github.com/interagent/committee/issues/339

**Comment by hlascelles** [comment]
Terrific :rocket:. Let me know if we can help with this.

**Comment by ota42y** [comment]
That's very nice of you to say !!!
If you are interested, you can try to implement this feature.
