### ISSUE TITLE
Middleware deprecation warnings are confusing

### ISSUE THREAD

**Issue by acceptto-nhumble** [interagent/committee#362]
If you use `Committee::Middleware::RequestValidation` you get a deprecation warning telling you to "please set parse_response_by_content_type = false because we'll change default value in next major version." which doesn't make sense in this context. That's not even listed as an option for that middleware. I think you're using the same options validation logic for all the middleware, which leads to warnings that make no sense. I can silence the warning by setting that value, but does it make sense to tell users to set an option that has no bearing on the middleware they're using?

It would be best if the options validation was aware of which middleware it was validating for so that it could give the correct responses. It could even warn about using options intended for other middleware. If you need any more information, please let me know and I am happy to help.

**Comment by madleech** [comment]
Agreed, setting options that aren't actually options looks wrong:
```ruby
  use Committee::Middleware::RequestValidation, schema_path: SCHEMA_PATH, strict: true, query_hash_key: 'rack.request.query_hash', parse_response_by_content_type: true
  use Committee::Middleware::ResponseValidation, schema_path: SCHEMA_PATH, query_hash_key: 'rack.request.query_hash', parse_response_by_content_type: true
```

**Comment by ota42y** [comment]
OK, we don't need set `parse_response_by_content_type` on RequestMiddleware so I remove deprecated message in v4.99.1
https://github.com/interagent/committee/pull/383

https://rubygems.org/gems/committee/versions/4.99.1
