### ISSUE TITLE
Do you need maintainers?

### ISSUE THREAD

**Issue by gjtorikian** [interagent/committee#366]
There are a few open issues and PRs that solve issues; I'm volunteering to help merge/manage those. Ideally I would like to get this project updated to 5.x, and release support for OpenAPI 3.1.

Edit: @brandur @ota42y (pinging top contributors, sorry; I'm not sure who admins the repo) https://github.com/interagent/committee/pull/349 is a good example of a PR where the work is done, but needs merging. I can always pin to a ref and move on with my day, but I would rather help get these released. ✌️

**Comment by tyler-wel** [comment]
@ota42y @brandur safe to say you've abandoned the project?

**Comment by brandur** [comment]
@gjtorikian @tyler-wel Oof yeah, sorry I didn't see this before — I stepped away from this one quite a number of years ago and @ota42y de factor took over.

@ota42y Do you have any thoughts on finding alternative maintainers?

**Comment by ota42y** [comment]
Sorry, I hadn't checked for a while and hadn't noticed (a kind friend told me about this Issue).
Will check this weekend!

However, there is a problem with the maintainer. I have not used Ruby recently and would like a maintainer who is actively using Ruby.

**Comment by gjtorikian** [comment]
> I have not used Ruby recently and would like a maintainer who is actively using Ruby.

I don't know how to prove it, but I still actively write and release Ruby gems, like:

* https://github.com/gjtorikian/commonmarker
* https://github.com/gjtorikian/selma
* https://github.com/gjtorikian/html-pipeline

I will say, though, that since I opened this issues, I found https://github.com/ahx/openapi_first, which also has a nice comparison of supported features: https://gist.github.com/ahx/1538c31f0652f459861713b5259e366a

So while I can still volunteer to modernize/admin this gem I myself am no longer using it. 🤷‍♂️ I think probably much of this gem depends on https://github.com/ota42y/openapi_parser, which also has some open PRs associated with it.

**Comment by ota42y** [comment]
@gjtorikian 
We think you have great skills!
I would like to ask for your help, especially since there are not many people who know much about OpenAPI.

> I think probably much of this gem depends on https://github.com/ota42y/openapi_parser, which also has some open PRs associated with it.

Yes, we have implemented the OpenAPI implementation as a separate gem for OpenAPI 3 support. Therefore, the committee itself is focused on exchanging requests and responses with rack.

**Comment by gjtorikian** [comment]
> I would like to ask for your help, especially since there are not many people who know much about OpenAPI.


Ok, than I humbly accept! 😄

**Comment by ota42y** [comment]
@brandur Can you give @gjtorikian  write access to this repository?

Any ideas on how to work with us?
If we are going to write code, Issues with a [ready tag](https://github.com/interagent/committee/issues?q=is%3Aissue+is%3Aopen+label%3Aready) are the ones that are clear on what needs to be done.
It might be a good idea to have him look through the PRs and Issues that are open.

Currently I am going to release v5.0.0 in its current master code state, but I have no idea what features I will add next version.

**Comment by brandur** [comment]
@ota42y @gjtorikian Added!

**Comment by geemus** [comment]
I'm going to close this as it looks like everything was resolved at the time.
