### ISSUE TITLE
RequestValidation middleware and error responses

### ISSUE THREAD

**Issue by dpiddy** [interagent/committee#42]
Using the `RequestValidation` middleware with `raise: true` works fine for successful responses but breaks down a bit for errors. For example, say I want to return this from my app's `GET /apps` endpoint:

```
404 Not Found
{
  "id": "not_found",
  "message": "app not found"
}
```

It fails validation since my schema says `GET /apps` will return something that looks like an app.

I initially see a few options for this:

* add a way to skip validation of non-2xx responses (and maybe make it the default?)
* add an `error_schema` param that is expected to contain the schema for all non-2xx responses
* use `anyOf` in my schema to say all links can return a successful representation or an error representation

I think the third is an interesting long-term option but I'll probably start by trying out the first.

Thoughts?

**Comment by brandur** [comment]
Closing this as fixed by #43.
