### ISSUE TITLE
tidelift funding?

### ISSUE THREAD

**Issue by geemus** [interagent/committee#432]
For some of my other packages I receive funding from Tidelift to meet and maintain certain industry standards. I was considering doing this for committee as well, but wanted to check in with other folks here since there have been quite a few people involved and maintaining at different times.

Would other maintainers be ok if I claimed that responsibility and the funding that comes along with it (it's currently estimated to be $50/month)?

You can see more about the program here: https://tidelift.com/about/lifter

**Comment by brandur** [comment]
Wes, I'm not too sure about this one, or at least. yet. This project's been maintained by various people for years. I know you've stepped in to pull in a few changes more lately (and thank you for that!), but it's only been a handful of commits so far, and it's all very recent (I think you became active again on Oct 9th if I'm reading this right?), so there isn't much of a historical track record we can point to.

Beyond that, I'd fear a little that bringing money into the equation and having it distributed one way will somewhat discourage other maintainers like @ydah from keeping an active hands in things. (i.e. "If someone else is getting paid for this, why am I the one volunteering my time?")

I'd suggest that we broach this again when we have a little more historical data to look at, and make sure there's unanimous buy in amongst maintainers active in say, the last six months or something like that.

I'd personally also want to make sure there's a process for unwinding funding should that become appropriate. One thing we've seen 3-4 times now on this project is people stepping up to become maintainers, doing it for a while, but then dropping back out again. This never happens with an official resignation ... it's more like like they become less active over time and eventually unresponsive. That's totally fine, but if were to happen with Tidelift engaged, any associated money should also stop of course.

**Comment by geemus** [comment]
@brandur Sure, seems totally reasonable, I mostly wanted to start the conversation. It's certainly much more complicated in this case than with other projects where I've been the primary author/maintainer for their whole lifetimes.

The money is available, so it seemed worth asking if I could claim it. I don't intend for whether or not I do to impact my involvement. I'm now using committee again both at my day job and in consulting, in addition to my previous engagement with it. So I'm hoping to be around more and for a while regardless. Though honestly, I didn't exactly intend to stop working on it before, it just drifted further and further away from my focus, and that could certainly happen again in the future.

I definitely don't want to discourage others from engaging either. I'm open to splitting the money and responsibility to if people want to as well. I admit it's somewhat new terrain. Also, I'm not sure if it makes that much of a difference, but there are specific responsibilities above and beyond general maintenance that are expected (mostly related to security and backporting things).

In terms of unwinding, my understanding is that you can officially step down from Tidelift with a bit of warning and/or they will remove you if you are unresponsive to requests for some period of time. I'm less certain about how this works if it is instead transitioning from one maintainer to another. There might not be a clear cut answer here, Tidelift seems to do things like this in a pretty high touch, human way. So there is possibility to talk with them and get help navigating things if it comes to it.

**Comment by ydah** [comment]
I don't necessarily need money as direct compensation for the development of open source software, and I have no problem with other maintainers of the committee getting paid.

I don't particularly care if other maintainers charge and receive money. Developing open source software is a hobby of mine 👍🏻　

You can proceeds and do it without worrying about me, but I honestly can't image how future maintainers will feel about it yet.

**Comment by geemus** [comment]
@ydah thanks for weighing in. Definitely hard to know how future folks will feel.

I guess I haven't exactly had to explain Tidelift or my engagement all that much, so maybe I'll try in a bit more depth. Apologies if I flubbed it a bit so far.

Overall I still try to engage with open source in hobby-like way. I care about it and have worked in and around it for many years because I find it interesting and rewarding. I don't want money to change that, and hope that I'll still engage regardless of payment.

That said, when I found out about Tidelift it seemed like it might be a nice kind of win-win. Their focus is mostly around providing more enterprise desired things within open source. Many of these are good things to do, particularly around security and governance, but not things I was motivated to do as a hobbyist. The money compensates for doing those changes, maintaining them, and giving companies that might rely on the software some assurance that if they need to call upon someone to respond to a security issue, for instance, that there is a good chance somebody will answer. I also hope that this will be good for the projects in general, as having better security/governance/etc can also boost adoption.

At present, and often (but not always) in the past, I've had the benefit of supportive employers that allow me to spend some time on a regular basis doing open source. Without that, I think it could really be a struggle for me to find the time at present (I have two young kids). This felt particularly stark when I was laid off a couple of years ago and wanted to work on open source, but often felt torn between that and the job hunt. I'm hoping that having a little ongoing income from things like this can give me and my family a bit more security and also give me some more options should my job situation change once more.

If I accepted the money here, I would follow up with those security/governance things that would be nice to have (but not probably required, we've gotten by this far), and I would be committing to respond to security and other urgent things. If I don't accept the money, I still hope to help with bugs and releases (and even urgent things), but may not focus on the security/governance things since currently things seem largely good-enough.

Either way is fine. It's something I would take on if folks are ok with it, but not something I need to take on by any means. And I would only want to proceed if it was a win-win for the project overall, not just for myself and tidelift/enterprise folks. Certainly happy to provide more detail or discuss further if it would help.

**Comment by geemus** [comment]
A couple of small updates (I asked Tidelift for clarifications on some of the questions).

1. They are able to customize and change split percentages among maintainers pretty easily. So if it came to that we could tweak it, they just ask that it be relatively stable (ie they don't want to have to update things every month).
2. Changing or transferring payment between maintainers can be handled with support tickets.
3. They do monitor the required tasks and will remove their support if they aren't completed. So even without transferring/changing, if the work wasn't getting done the payments would stop as well (which could also free them up if someone else wanted to claim them).

Overall, I've had really positive interactions with the Tidelift team. They are very supportive and flexible, so I'm confident we could work with them to figure out edge cases if/when they might occur.

**Comment by ydah** [comment]
Thank you very much! I think you can apply.  I respect your choices👍️

**Comment by geemus** [comment]
Thanks, I appreciate it. I don't want to proceed unless @brandur feels comfortable as well though.

**Comment by brandur** [comment]
@geemus Okay Wes, thanks for the thoughtful responses and follow up. Given @ydah is also on board, I withdraw my initial objection. +1.

**Comment by geemus** [comment]
@brandur thanks, I'll proceed then. Just let me know if you ever have further questions/concerns.
