### ISSUE TITLE
Request mime type validation a bit too strict. Should allow `charset`

### ISSUE THREAD

**Issue by amerine** [interagent/committee#51]
Hey Folks,

I was poking around the request validation code a couple weeks ago and made a little `TODO` in my notebook to look back at this mime type validation line when I had the time. Well, today I had the time.

A little backstory:
[Committee uses rack for request validation](https://github.com/interagent/committee/blob/e3739b6751ce56163241cea70607d90b788b593c/lib/committee/request_validator.rb#L22) of the mime type. [Currently rack will compare](https://github.com/rack/rack/blob/master/lib/rack/mime.rb#L28-L33) a check for `application/json` with `"application/json"`, and `"application/*"` or `"*"` and all will return true. This is fine and awesome. The `type` and `subtype` **should** match when we're validating the the `Content-Type` is what the schema defines. 

The problem:
The issue here is that there are additional `parameters` that can be passed along with the Content-Type. Specifically the error case that I have is when specifying the `charset` for an `"application/json"` request. This mean is that if I make a request with `"application/json; charset=utf8"` and I have the request validation middleware running, all my requests will fail.

I think this is too strict.

`"application/json"` & `"application/json; charset=utf8"` are inherently the same type/subtype. The parameter is this case is there to help inform the host of encoding but does not change the Content-Type the host expects.

Generally I would have just sent up a PR with a change stripping the parameters from the Content-Type header, but I wanted to chat about if we should be doing that in committee or in rack... or if my opinion is wrong. Thoughts?

**Comment by nwjsmith** [comment]
I think https://github.com/interagent/committee/pull/65 fixes this

**Comment by dpiddy** [comment]
I believe so!
