### ISSUE TITLE
Status 204 (No Content) raises Committee::InvalidResponse

### ISSUE THREAD

**Issue by ronen** [interagent/committee#58]
I've got an API call that returns status 204 (no content), and  ResponseValidation raises`Committee:InvalidResponse` 

The culprit is:

https://github.com/interagent/committee/blob/69708a870b341ea3128be113654e0259ca14b583/lib/committee/middleware/response_validation.rb#L17

            data = MultiJson.decode(full_body)

With no content, `full_body` is an empty string and so `MultiJson.decode(full_body)` raises`MultiJson::LoadError`.

I've made a quick patch to address this, by skipping validation if status is 204.  I put it in a separate PR, since I could imagine you might want to address this in some other way.    In particular, it could perhaps be more robust to allow `targetSchema` to specify no content somehow (via `"type": "null"` ?), and then explicitly validate that there is no content.

**Comment by nwjsmith** [comment]
I believe this is fixed in #59

**Comment by geemus** [comment]
I believe you are correct.
