### ISSUE TITLE
Pluggable error responses?

### ISSUE THREAD

**Issue by nwjsmith** [interagent/committee#68]
Would there be interest in having pluggable error responses? Right now we're using Committee on an API adhering to JSON API, which [specifies it's own error format](http://jsonapi.org/format/#errors). I can add this functionality, just want to be sure it's something y'all would be interested in.

**Comment by brandur** [comment]
@nwjsmith Excellent idea! I'd definitely be receptive to this.

I mostly built the currently error responses around what we were doing with the Heroku API, but knew full well at the time that this wouldn't be suitable for everybody. Committee's designed to be as general purpose as possible when it comes to adherence to JSON Hyperschema, so it should probably allow for the full range of spec-compliant implementations.

**Comment by swalkinshaw** [comment]
This can be closed after #72 was merged.

**Comment by brandur** [comment]
@swalkinshaw Good call. Thank-you.
