### ISSUE TITLE
Pull 1.7.0 release

### ISSUE THREAD

**Issue by nwjsmith** [interagent/committee#69]
Since the latest release of committee is 1.6.5, could the 1.7.0 release be removed from rubygems (or 1.7.1 pushed out?). I think things are out of order because of https://github.com/interagent/committee/issues/66. /cc @brandur

**Comment by nwjsmith** [comment]
On second thought, it's probably much better to push out 1.7.1 than to pull 1.7.0

**Comment by brandur** [comment]
@nwjsmith Wow, did I screw this up again?! Sorry about that. Pushed 1.7.1 to Rubygems and the appropriate commit/tag up to this repo. Thanks!
