### ISSUE TITLE
support for swagger json schema

### ISSUE THREAD

**Issue by gregory** [interagent/committee#73]
Hey guys ,
just wondering if this supports [swagger json schema](https://github.com/swagger-api/swagger-spec/blob/master/schemas/v2.0/schema.json) ? 

In fact i'm thinking of a workflow where i'd first design my API with the [swagger editor](http://editor.swagger.io/#/) then extract the schema and push a mock server based on that on heroku and focus on the front end, with something like middleman... 

cc @mattolson

**Comment by geemus** [comment]
We haven't really explored providing swagger related functionality here. The json-schema itself there should work, just as any other json-schema would, but it wouldn't have any of the swagger specifics in place I don't think.

**Comment by brandur** [comment]
This is hugely late, but I'm interested in implementing this, and expect to have something in place in the coming months.
