### ISSUE TITLE
Freezes (100% CPU) inspecting a Middleware

### ISSUE THREAD

**Issue by mcclymont** [interagent/committee#77]
Ever since adding committee to our Rails app (then Rails 3, now Rails 4) we have been having a very annoying issue: if we have a typo or other mistake during development where we refer to a non-existent method or variable, the application becomes unresponsive and goes to 100% CPU, requiring a ctrl C and sometimes a kill -9.

Our config/application.rb has the following:
```
config.middleware.use ::Committee::Middleware::RequestValidation,
      :schema => JSON.parse(File.read(schema_path)),
      :prefix => "/api/v1"
```
and I confirmed the issue is related to Committee by taking out this line, and the problem going away.

I'm not sure exactly how the call stack gets there, but somewhere in Rack or Rails as part of dealing with a NoMethodError, it ends up calling .inspect on the instance of RequestValidation. (Edit - it is probably the view that presents contents of request, env etc. for debugging errors in dev, or something like NewRelic while in production) This, in turn calls .inspect on the instance variables including @schema and @router. These 2 in particular are problems because they contain JsonSchema::Schema objects. I actually tracked down the problem to coming from json_schema itself, in that the JsonSchema::Schema#inspect is incredibly verbose, and in any non-trivial schemas it appears to lock-up my system. I think this has something to do with the recursive nature of schemas that reference each other.

I have a repo here that demonstrates the issue: https://github.com/mcclymont/rails4-routing-example. I used the heroku schema as it is public. It is considerably larger than the schema we are using for our internal project.

I'm not sure if json_schema is maintained by the same team as committee. If so, maybe we can fix how json_schema is inspected, if there is a problem. Otherwise committee could implement its own #inspect and not inspect the JsonSchema stuff

**Comment by geemus** [comment]
Hmm. @brandur could you take a look? Thanks!

**Comment by brandur** [comment]
Hi Chris,

My apologies for the delay on this one.

Like you suggested, I've simplified the `#inspect` method in `json_schema` so that it doesn't try its crazy recursive work anymore. After release brandur/json_schema#29` and 9cbdd8606d771593c4898f8cbd68478b36e828ee, I've confirmed that the problem no longer occurs in your reproduction suite.

Thanks for the detailed bug report!
