### ISSUE TITLE
Query parameters are not supported

### ISSUE THREAD

**Issue by smoak** [interagent/committee#79]
Consider the following link to search for a car based on color and number of doors:

```json
links: [
    {
        "description": "Find",
        "href": "/cars?color={(%23%2Fdefinitions%2Fcars%2Fdefinitions%2Fcolor)}&door={(%23%2Fdefinitions%2Fcars%2Fdefinitions%2Fdoor)}",
        "method": "GET",
        "rel": "self",
        "title": "search"
    }
]
```

If I use committees test method `assert_schema_conform`, it raises an error:

```ruby
Failure/Error: assert_schema_conform
     Committee::InvalidResponse:
       `GET /cars` undefined in schema.
```

Is there perhaps a better way of doing this?

**Comment by brandur** [comment]
@smoak Oh wow, yeah right now Committee just looks at those hrefs as queryless URIs.

It might be worth considering that the `schema` property is also allowed to define a query string encoded schema for a GET request. This might be an alternative option here that's worth exploring:

http://json-schema.org/latest/json-schema-hypermedia.html#anchor38

**Comment by smoak** [comment]
I think that suggestion will work.

**Comment by smoak** [comment]
Yep. That suggestion works. Thanks.

**Comment by brandur** [comment]
Good to hear! Thanks.
