### ISSUE TITLE
Rack Param and RequestValidator

### ISSUE THREAD

**Issue by kyprifog** [interagent/committee#94]
We use PRMD to generate our json schema and documentation so the schema has specificity on the type of the request parameters, and furthermore we want to validate the type.  However Rack:Utils.parse_nested_query makes all request parameters "string" type. This means that if our schema has specified an integer type and even if the rspec test specifies an integer it will still get passed through by Rack as a string and then committee will throw a RequestValidation error:

```
#rspec
patch "/test_endpoint", test_param: 451

>> #/test_endpoint: failed schema #/definitions/test_endpoint/links/6/schema/properties/test_param: For 'properties/test_param', "451" is not an integer.
```

This seems like a general issue in using request validation with Rack/rspec.  What am I missing here?

**Comment by kyprifog** [comment]
Never mind, I need to specify application/json media type, rspec is defaulting to form-encoded.

**Comment by brandur** [comment]
Oops, yeah that one is a bit of a gotcha. Glad that you got it figured out!
