### ISSUE TITLE
Can this be an alternative to Rails's Strong Parameters?

### ISSUE THREAD

**Issue by qsona** [interagent/committee#98]
Hi, I'm using Rails (5). I want to validate request, but also want to pick only defined keys by using json schema.

For example: 

the json schema defines `a` key as required and `b` key as optional.
the http request params is `{ a: 1, b: 2, c: 3 }`
=> I'm happy if the `params` (which can be used in controller) is `{ a: 1, b: 2 }`.
Then I don't need to use Strong Parameters of Rails. 

If not, I may have to implement same validation logic as json schema to controllers using Strong Parameters.
Does committee have such a feature?
If not, do you think the feature is useful and can be implemented?

Thank you.

**Comment by brandur** [comment]
Hi @qsona,

So I don't have any particular experience with Rails compatibility, but yes, it should work (in theory). You can drop the gem into your middleware stack as described here:

https://github.com/interagent/committee#committeemiddlewarerequestvalidation

And it will start to allow or reject requests the same as any other stack.

I'm going to close this issue down, but let me know if you have any other questions.

**Comment by qsona** [comment]
@brandur Thank you for your quick response and I'm sorry my response is late.

I meant that, if the request body json has some unnecessary keys, I want to treat the request as valid (and Committer seems to do so), but want to throw away those keys and force that we cannot get those keys/values from our application codes.

I created a schema like belows,
```js
// in `links`
"href": "/foo",
"method": "POST",
"rel": "create",
"schema": {
  "type": [
    "object"
  ],
  "properties": {
    "a": {
      "$ref": "#/definitions/xxx/definitions/a"
    },
    "b": {
      "$ref": "#/definitions/xxx/definitions/b"
    },
  },
  "required": [
    "a"
  ]
```
then prepare the code `puts params[:c]` in controller, and send request `POST /foo` with body `{"a":1,"b":2,"c":3}`.

The result of `puts params[:c]` is `3`, whereas I expect `nil` because `c` is not a defined key.

What do you think?

**Comment by brandur** [comment]
Hi @qsona,

Have you seen the [`additionalProperties` keyword in JSON schema](https://github.com/json-schema/json-schema/wiki/Additionalproperties)?

Committee is letting those requests through because technically any objects with extra properties are still valid unless `additionalProperties` has been set to `false`. This might be what you're looking for here.

**Comment by qsona** [comment]
I just found I forgot to reply. At that time I know about additionalProperties but didn't think about it at all. Thank you for pointing this out.
